# This is a basic workflow to help you get started with Actions

name: Pack and publish nuget package

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: git tag you want create. (sample 1.0.0)"
        required: true
      dry_run:
        description: "dry_run: true will never create relase/nuget."
        required: true
        default: "false"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    if: "!(contains(github.event.head_commit.message, '[skip ci]'))"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.202
    - name: Build
      run: dotnet build ./src/SplitJs.Blazor/SplitJs.Blazor.csproj --configuration Release
    - name: Pack
      run: dotnet pack ./src/SplitJs.Blazor/SplitJs.Blazor.csproj  --output ./artifacts --configuration Release
    - name: Publish
      run: dotnet nuget push ./artifacts/$(ls ./artifacts | grep .nupkg) --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
